/*
  # Create Tournament Draft (RPC)

  Creates a draft tournament and automatically adds the creator as a participant.
  Also enforces the global per-user tournament cap (4) based on draft/active participation.
*/

CREATE OR REPLACE FUNCTION create_tournament_draft(
  p_name text,
  p_start_date date,
  p_end_date date
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user_id uuid := auth.uid();
  v_tournament_id uuid;
  v_active_count integer;
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  IF p_name IS NULL OR length(trim(p_name)) = 0 THEN
    RAISE EXCEPTION 'Tournament name is required';
  END IF;

  IF p_end_date < p_start_date THEN
    RAISE EXCEPTION 'Invalid date range';
  END IF;

  -- Enforce max 4 tournaments per user (draft + active), based on participation.
  SELECT COUNT(*)
  INTO v_active_count
  FROM tournament_participants tp
  JOIN tournaments t ON t.id = tp.tournament_id
  WHERE tp.user_id = v_user_id
    AND t.status IN ('draft', 'active');

  IF v_active_count >= 4 THEN
    RAISE EXCEPTION 'You are already in the maximum number of tournaments (4)';
  END IF;

  -- Create tournament (join_code generated by default)
  INSERT INTO tournaments (name, start_date, end_date, status, created_by)
  VALUES (trim(p_name), p_start_date, p_end_date, 'draft', v_user_id)
  RETURNING id INTO v_tournament_id;

  -- Add creator as a participant
  INSERT INTO tournament_participants (tournament_id, user_id)
  VALUES (v_tournament_id, v_user_id);

  RETURN v_tournament_id;
END;
$$;

REVOKE ALL ON FUNCTION create_tournament_draft(text, date, date) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION create_tournament_draft(text, date, date) TO authenticated;

